spring:
  application:
    name: campaign_controller_api_rest
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog.sql

server:
  port: 8000

# Google Ads API configuration
api:
  googleads:
    enabled: false  # Set to true and provide credentials to enable Google Ads API

# OpenAPI properties
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
    path: /swagger-ui
  api-docs:
    path: /api-docs
